2020-08-19 15:42:36,139 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-19 15:46:05,924 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-19 15:49:23,920 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-19 15:50:11,189 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-19 16:02:16,209 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-19 16:02:31,820 - INFO - 127.0.0.1 - - [19/Aug/2020 16:02:31] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-19 16:02:33,986 - INFO - 127.0.0.1 - - [19/Aug/2020 16:02:33] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-19 16:02:35,035 - INFO - 127.0.0.1 - - [19/Aug/2020 16:02:35] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-19 16:02:39,826 - DEBUG - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 30
2020-08-19 16:02:39,828 - INFO - 127.0.0.1 - - [19/Aug/2020 16:02:39] "[32mPOST /delete_data HTTP/1.1[0m" 302 -
2020-08-19 16:02:39,843 - INFO - 127.0.0.1 - - [19/Aug/2020 16:02:39] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-19 16:06:01,888 - INFO - 127.0.0.1 - - [19/Aug/2020 16:06:01] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-20 17:29:40,190 - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-20 18:15:08,903 - WARNING - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 33
2020-08-20 18:16:55,549 - DEBUG - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 34
2020-08-20 18:17:50,471 - DEBUG - db - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 29
2020-08-20 18:18:34,466 - DEBUG - db - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 35
2020-08-20 18:43:58,650 - DEBUG - __main__ - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö (36, 48.0, 0.66, datetime.datetime(2020, 8, 20, 18, 18, 27), '–¥–æ—Ö–æ–¥', '–±—É—Ä–≥–µ—Ä')
2020-08-20 18:44:00,371 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞ (36, 38.0, 0.52, datetime.datetime(2020, 8, 20, 18, 44), '—Ä–∞—Å—Ö–æ–¥', '–¥–æ–ª–≥')
2020-08-20 19:04:31,531 - DEBUG - logger - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö (36, 38.0, 0.52, datetime.datetime(2020, 8, 20, 18, 44), '—Ä–∞—Å—Ö–æ–¥', '–¥–æ–ª–≥')
2020-08-20 19:04:33,870 - DEBUG - logger - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞ (36, 48.0, 0.66, datetime.datetime(2020, 8, 20, 19, 4, 33), '–¥–æ—Ö–æ–¥', '–±–∞–ª–∞–Ω—Å —Ç–µ–ª–µ—Ñ–æ–Ω–∞')
2020-08-20 19:14:01,585 - INFO - werkzeug -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-08-20 19:14:03,846 - INFO - werkzeug - 127.0.0.1 - - [20/Aug/2020 19:14:03] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-20 19:14:20,534 - DEBUG - root - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö (36, 48.0, 0.66, datetime.datetime(2020, 8, 20, 19, 4, 33), '–¥–æ—Ö–æ–¥', '–±–∞–ª–∞–Ω—Å —Ç–µ–ª–µ—Ñ–æ–Ω–∞')
2020-08-20 19:14:20,540 - DEBUG - urllib3.connectionpool - Starting new HTTPS connection (1): www.banki.ru:443
2020-08-20 19:14:22,010 - DEBUG - urllib3.connectionpool - https://www.banki.ru:443 "GET /products/currency/usd/ HTTP/1.1" 200 None
2020-08-20 19:14:22,036 - DEBUG - root - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞ (36, 56.0, 0.76, datetime.datetime(2020, 8, 20, 19, 14, 22), '—Ä–∞—Å—Ö–æ–¥', '–±—É—Ä–≥–µ—Ä')
2020-08-20 19:14:22,037 - INFO - werkzeug - 127.0.0.1 - - [20/Aug/2020 19:14:22] "[32mPOST /update_data HTTP/1.1[0m" 302 -
2020-08-20 19:14:22,057 - INFO - werkzeug - 127.0.0.1 - - [20/Aug/2020 19:14:22] "[37mGET / HTTP/1.1[0m" 200 -
2020-08-20 19:18:32,258 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 81, in update_data
    logger.debug(f"–ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö {data_id}")
NameError: name 'logger' is not defined
2020-08-20 19:19:38,804 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö (36, 56.0, 0.76, datetime.datetime(2020, 8, 20, 19, 14, 22), '—Ä–∞—Å—Ö–æ–¥', '–±—É—Ä–≥–µ—Ä')
2020-08-20 19:19:40,081 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞ (36, 48.0, 0.66, datetime.datetime(2020, 8, 20, 19, 19, 40), '–¥–æ—Ö–æ–¥', '–æ–≥—Ä–∞–±–ª–µ–Ω–∏–µ')
2020-08-26 13:22:18,845 - WARNING - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω—ã—Ö (36, 48.0, 0.66, datetime.datetime(2020, 8, 20, 19, 19, 40), '–¥–æ—Ö–æ–¥', '–æ–≥—Ä–∞–±–ª–µ–Ω–∏–µ')
2020-08-26 13:22:21,065 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞ (36, 102.0, 1.37, datetime.datetime(2020, 8, 26, 13, 22, 20), '—Ä–∞—Å—Ö–æ–¥', '–±—É—Ä–≥–µ—Ä')
2020-08-26 13:33:17,631 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 82, in update_data
    logger_expenses.debug(f"–ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id {line_d}: rubles = {data_id[1]}, dollars = {data_id[2]}, date = {data_id[3]}, w/i = {data_id[4]}, description = {data_id[5]}")
NameError: name 'line_d' is not defined
2020-08-26 13:34:02,116 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 36: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:22:20, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 13:34:04,476 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 48.0, dollars = 0.64, date = 2020-08-26 13:34:04, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-08-26 13:36:38,978 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 36: rubles = 48.0, dollars = 0.64, date = 2020-08-26 13:34:04, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-08-26 13:36:40,675 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 101, in update_data
    dollars = round(rubles / get_dollar_value(), 2)
  File "expenses.py", line 34, in get_dollar_value
    dollar_html = requests.get("https://www.banki.ru/products/currency/usd/")
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-08-26 13:38:10,851 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 36: rubles = 48.0, dollars = 0.64, date = 2020-08-26 13:34:04, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-08-26 13:38:13,019 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:38:13, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 13:49:19,744 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 36: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:38:13, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 13:49:20,580 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 48.0, dollars = 0.64, date = 2020-08-26 13:49:20, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-08-26 13:50:09,856 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 36: rubles = 48.0, dollars = 0.64, date = 2020-08-26 13:49:20, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-08-26 13:50:11,699 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 104, in update_data
    update_line(rubles, waste_or_income, description, dollars, line_id)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 83, in update_line
    logger_db.debug(f"–î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: "
NameError: name 'new_dat' is not defined
2020-08-26 14:03:04,023 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-26 14:06:45,633 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-26 14:20:30,898 - WARNING - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 321.0, dollars = 4.31, date = 2020-08-26 14:20:30, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 14:33:53,878 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 39: rubles = 321.0, dollars = 4.31, date = 2020-08-26 14:20:30, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 14:33:55,518 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.37, date = 2020-08-26 14:33:55, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 14:37:38,640 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 39: rubles = 102.0, dollars = 1.37, date = 2020-08-26 14:33:55, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-26 14:37:40,261 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 104, in update_data
    update_line(rubles, waste_or_income, description, dollars, line_id)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 82, in update_line
    logger_db.debug(f"–î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: "
NameError: name 'new_dat' is not defined
2020-08-26 14:38:51,762 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-30 23:27:09,025 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-30 23:28:03,032 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 00:25:33,181 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 00:26:00,807 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 00:26:32,994 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 00:27:53,437 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 00:34:20,231 - ERROR - db - eror dada
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:35:27,306 - ERROR - db - eror dada Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:36:53,212 - ERROR - db - eror dada Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:38:41,994 - ERROR - db - eror dada
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:39:34,024 - ERROR - db - eror dada
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:40:24,013 - ERROR - db - eror dada Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:41:40,952 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:44:54,443 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 44, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 00:54:45,245 - DEBUG - db - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.37,w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-31 00:58:17,291 - ERROR - db - –û—à–∏–±–∫–∞: list index out of range
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 59, in delete_line_to_id
    delete_line = get_data_to_id(line_id)[0]
IndexError: list index out of range
2020-08-31 01:01:29,203 - DEBUG - expenses - –£–ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 39, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 321.0, dollars = 4.31, date = 2020-08-26 14:37:40, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-08-31 01:01:29,226 - DEBUG - db - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 39
2020-08-31 19:54:04,881 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 19:54:59,312 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 19:55:43,849 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 19:57:25,180 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 19:57:56,876 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 19:58:33,718 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 20:00:11,046 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 20:00:54,124 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(quer, (rubles, dollars, waste_or_income, description))
NameError: name 'quer' is not defined
2020-08-31 20:01:32,157 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 20:02:15,577 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 20:02:53,190 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-08-31 20:08:37,996 - WARNING - db - y cyka
2020-08-31 20:09:02,247 - WARNING - db - y cyka
2020-08-31 20:09:12,351 - WARNING - db - y cyka
2020-09-01 22:44:10,089 - WARNING - db - y cyka
2020-09-01 22:44:34,125 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-01 22:44:57,327 - WARNING - db - y cyka
2020-09-01 22:45:05,101 - DEBUG - db - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.38, w/i = –¥–æ—Ö–æ–¥, description = –¥–æ–ª–≥
2020-09-01 22:45:12,375 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 36, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:50:11, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-01 22:45:12,425 - DEBUG - db - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 36
2020-09-01 22:45:34,064 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 37: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:59:56, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-01 22:45:34,064 - ERROR - expenses - Exception on /update_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 99, in update_data
    waste_or_income = data_id[4]
NameError: name 'data_id' is not defined
2020-09-01 22:51:09,191 - WARNING - db - y cyka
2020-09-01 22:51:21,538 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 37: rubles = 102.0, dollars = 1.37, date = 2020-08-26 13:59:56, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-01 22:51:23,075 - DEBUG - db - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 321.0, dollars = 4.35, date = 2020-09-01 22:51:23, w/i = –¥–æ—Ö–æ–¥, description = –∑–ø
2020-09-01 22:56:27,513 - WARNING - db - y cyka
2020-09-01 23:18:50,435 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-01 23:19:04,036 - DEBUG - db - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.38, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 00:05:21,705 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:05:31,310 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 47, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:05:31,312 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 47, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 55, in add_line
    @app.route('/error')
NameError: name 'app' is not defined
2020-09-02 00:12:44,095 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:14:16,536 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:14:29,008 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 52, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:16:13,736 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:16:26,313 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 49, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:36:52,889 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:37:04,060 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 49, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:37:04,063 - ERROR - expenses - Exception on /add_data [POST]
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-09-02 00:40:37,674 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:40:48,318 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 49, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:41:35,978 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:41:43,905 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 49, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 00:42:22,146 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 00:42:30,632 - ERROR - db - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 49, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 22:07:35,203 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 22:18:08,863 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 22:18:30,492 - ERROR - expenses - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "expenses.py", line 58, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 46, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 22:18:51,582 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 22:19:05,512 - DEBUG - db - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = —Ä–∞—Å—Ö–æ–¥, description = –∫–æ–ª–∞
2020-09-02 22:25:42,047 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 22:25:52,316 - DEBUG - db - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = –¥–æ—Ö–æ–¥, description = –∑–ø
2020-09-02 22:25:52,316 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = –¥–æ—Ö–æ–¥, description = –∑–ø
2020-09-02 22:28:40,756 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 22:28:49,831 - ERROR - expenses - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "expenses.py", line 58, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 43, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 23:01:26,385 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:01:36,486 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:01:42,772 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 42, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.38, date = 2020-09-01 23:19:03, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:01:42,815 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 42
2020-09-02 23:01:56,028 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 43: rubles = 102.0, dollars = 1.39, date = 2020-09-02 22:19:05, w/i = —Ä–∞—Å—Ö–æ–¥, description = –∫–æ–ª–∞
2020-09-02 23:01:58,071 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.39, date = 2020-09-02 22:19:05, w/i = —Ä–∞—Å—Ö–æ–¥, description = –∫–æ–ª–∞
2020-09-02 23:02:03,706 - DEBUG - expenses - –í—Å–µ –¥–∞–Ω–Ω—ã–µ —É–¥–∞–ª–µ–Ω—ã
2020-09-02 23:02:38,495 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:02:48,608 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 321.0, dollars = 4.36, w/i = –¥–æ—Ö–æ–¥, description = –∑–ø
2020-09-02 23:02:56,277 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 48.0, dollars = 0.65, w/i = —Ä–∞—Å—Ö–æ–¥, description = –∫–æ–ª–∞
2020-09-02 23:03:05,621 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 123.0, dollars = 1.67, w/i = –¥–æ—Ö–æ–¥, description = –æ–≥—Ä–∞–±–ª–µ–Ω–∏–µ
2020-09-02 23:05:27,383 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:05:35,634 - ERROR - expenses - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "expenses.py", line 57, in add_data
    add_line(rubles, dollars, waste_or_income, description)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 45, in add_line
    mysql_cursor.execute(query, (rubles, dollars, waste_or_income, description))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 23:05:45,081 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 46, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:02:38, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:05:45,084 - ERROR - expenses - –û—à–∏–±–∫–∞: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELE FROM expenses WHERE id = 46' at line 1
Traceback (most recent call last):
  File "expenses.py", line 79, in delete_data
    delete_line_to_id(line_id)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 51, in delete_line_to_id
    mysql_cursor.execute(query)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELE FROM expenses WHERE id = 46' at line 1
2020-09-02 23:06:03,009 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 46: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:02:38, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:06:04,516 - ERROR - expenses - –û—à–∏–±–∫–∞: Not all parameters were used in the SQL statement
Traceback (most recent call last):
  File "expenses.py", line 125, in update_data
    update_line(rubles, waste_or_income, description, dollars, line_id)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 69, in update_line
    mysql_cursor.execute(query, (rubles, waste_or_income, description, dollars, line_id))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 542, in execute
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
2020-09-02 23:06:12,540 - ERROR - expenses - –û—à–∏–±–∫–∞: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELE FROM expenses' at line 1
Traceback (most recent call last):
  File "expenses.py", line 91, in delete_all_data
    delete_all_lines()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 57, in delete_all_lines
    mysql_cursor.execute(query)
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELE FROM expenses' at line 1
2020-09-02 23:06:58,921 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:07:15,338 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = , description = 
2020-09-02 23:07:28,200 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 50, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:07:15, w/i = , description = 
2020-09-02 23:07:28,205 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 50
2020-09-02 23:15:40,851 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:15:50,531 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 46: rubles = {change_line[1]}, dollars = {change_line[2]}, date = {change_line[3]}, w/i = {change_line[4]}, description = {change_line[5]}
2020-09-02 23:15:51,473 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = {change_line[1]}, dollars = {change_line[2]}, date = {change_line[3]}, w/i = {change_line[4]}, description = {change_line[5]}
2020-09-02 23:18:41,773 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:18:50,802 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 46: rubles = 48.0, dollars = 0.65, date = 2020-09-02 23:15:51, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:18:52,546 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 48.0, dollars = 0.65, date = 2020-09-02 23:15:51, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:21:17,462 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.39, w/i = —Ä–∞—Å—Ö–æ–¥, description = –¥–æ–ª–≥
2020-09-02 23:22:16,823 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 46: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:18:52, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:22:23,897 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:18:52, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:23:18,682 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-02 23:23:26,470 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 46: rubles = 48.0, dollars = 0.65, date = 2020-09-02 23:22:23, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-02 23:23:27,648 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:23:27, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-06 19:23:06,141 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-06 19:23:25,688 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 51, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.39, date = 2020-09-02 23:21:17, w/i = —Ä–∞—Å—Ö–æ–¥, description = –¥–æ–ª–≥
2020-09-06 19:23:25,752 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 51
2020-09-06 19:23:37,786 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.36, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-06 19:23:45,907 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 52: rubles = 102.0, dollars = 1.36, date = 2020-09-06 19:23:37, w/i = –¥–æ—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-06 19:23:49,821 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.36, date = 2020-09-06 19:23:49, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-06 19:27:04,801 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-06 19:27:15,885 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 52: rubles = 102.0, dollars = 1.36, date = 2020-09-06 19:23:49, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-06 19:27:16,517 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 56.0, dollars = 0.74, date = 2020-09-06 19:27:16, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-07 14:55:31,477 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-07 14:55:46,957 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ –∏–∑–º–µ–Ω–µ–Ω–∏–µ –¥–∞–Ω–Ω—ã—Ö –≤ —Å—Ç—Ä–æ–∫–µ —Å id 52: rubles = 56.0, dollars = 0.74, date = 2020-09-06 19:27:16, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-07 14:55:48,509 - DEBUG - expenses - –î–∞–Ω–Ω—ã–µ –∏–∑–º–µ–Ω–µ–Ω—ã –Ω–∞: rubles = 102.0, dollars = 1.36, date = 2020-09-07 14:55:48, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-07 16:48:20,826 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:32:42,332 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:32:53,840 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 52, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.36, date = 2020-09-07 14:55:48, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-08 15:32:53,922 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 52
2020-09-08 15:35:39,892 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:36:25,908 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 49, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 123.0, dollars = 1.67, date = 2020-09-02 23:03:05, w/i = –¥–æ—Ö–æ–¥, description = –æ–≥—Ä–∞–±–ª–µ–Ω–∏–µ
2020-09-08 15:36:25,944 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 49
2020-09-08 15:37:13,822 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:37:24,067 - DEBUG - expenses - –î–æ–±–∞–≤–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å –¥–∞–Ω–Ω—ã–º–∏: rubles = 102.0, dollars = 1.35, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-08 15:37:27,500 - DEBUG - expenses - –ó–∞–ø—Ä–æ—Å –Ω–∞ —É–¥–∞–ª–µ–Ω–∏–µ —Å—Ç—Ä–æ–∫–∏ —Å id 53, –¥–∞–Ω–Ω—ã–µ —Å—Ç—Ä–æ–∫–∏: rubles = 102.0, dollars = 1.35, date = 2020-09-08 15:37:24, w/i = —Ä–∞—Å—Ö–æ–¥, description = –±—É—Ä–≥–µ—Ä
2020-09-08 15:37:27,536 - DEBUG - expenses - –£–¥–∞–ª–µ–Ω–∞ —Å—Ç—Ä–æ–∫–∞ —Å id 53
2020-09-08 15:46:21,005 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:46:24,650 - ERROR - expenses - –û—à–∏–±–∫–∞: No result set to fetch from.
Traceback (most recent call last):
  File "expenses.py", line 61, in index
    all_data = get_all_data()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 27, in get_all_data
    return mysql_cursor.fetchall()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 881, in fetchall
    raise errors.InterfaceError("No result set to fetch from.")
mysql.connector.errors.InterfaceError: No result set to fetch from.
2020-09-08 15:47:02,575 - WARNING - db - –ü–û–ß–ï–ú–£???
2020-09-08 15:47:13,289 - ERROR - expenses - –û—à–∏–±–∫–∞: No result set to fetch from.
Traceback (most recent call last):
  File "expenses.py", line 61, in index
    all_data = get_all_data()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/web_page_expenses/db.py", line 27, in get_all_data
    return mysql_cursor.fetchall()
  File "/home/alexandr/–†–∞–±–æ—á–∏–π —Å—Ç–æ–ª/python/flask_app/env/lib/python3.8/site-packages/mysql/connector/cursor.py", line 881, in fetchall
    raise errors.InterfaceError("No result set to fetch from.")
mysql.connector.errors.InterfaceError: No result set to fetch from.
2020-09-08 15:48:45,641 - WARNING - db - –ü–û–ß–ï–ú–£???
